# Generated by Django 2.2.5 on 2020-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, null=True)),
                ('preco', models.CharField(max_length=10, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
    ]
